site:
  title: Cockpit Docs
  start_page: cockpit::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
  - url: https://github.com/bookwar/cockpit
    branches: asciidoc-guide
    start_path: doc/guide/antora
    worktrees: true
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
